version: 2.2.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
clone_depth: 1
init:
- ps: git version
install:
- ps: >-
    dotnet --version
build_script:
- ps: >-
    appveyor DownloadFile https://github.com/LongbowActions/appveyor/raw/master/build.ps1 build.ps1

    powershell .\build.ps1 Pack
test_script:
- ps: >-
    powershell .\build.ps1 UnitTest
artifacts:
- path: '**\*.nupkg'